### ISSUE TITLE
Incorrect Mixed weapons initiative

### ISSUE THREAD

**Issue by helg40k** [cilliancleland/clashculator#2]
Mixed weapons has initiative 1 in the app.

However in the Rulebooks they have initiative 2.

How to check:

'Rise of Eagles' rulebook.
p.15 - Mixed weapons trait rule

'Clash of Katanas' rulebook.
p.15 - Mixed weapons trait rule
p.165 - Melee Weapons table

Clashculator app.
1. Rise of Eagles - Spartacus - Armed mob - Weapon (initiative)
2. Clash of Katanas - Shimazu/Otomo/Chosokabe/Mori/Oda/Toyotomi/Tokugawa/Takeda/Uesugi/Hojo/Date - Support Ashigaru - Upgrade to mixed weapons (+1pts) - Weapon (initiative)
3. Clash of Katanas - Otomo/Chosokabe/Hojo/Date/Ikko Ikki/Iga/Wako - Ronin - Weapon (initiative)
4. Clash of Katanas - Mori - Pirates - Weapon (initiative)
5. Clash of Katanas - Ikko Ikki - Peasants - Weapon (initiative)
6. Clash of Katanas - Ikko Ikki - Followers - Weapon (initiative)
7. Clash of Katanas - Iga - Scouts & Spies - Upgrade to mixed weapons (+1pts) - Weapon (initiative)
8. Clash of Katanas - Iga/Joseon Koreans - Guerrillas - Weapon (initiative)
9. Clash of Katanas - Iga - Mixed Weapons Ji-Samurai - Weapon (initiative)
10. Clash of Katanas - Iga/Wako - Bandits - Weapon (initiative)
11. Clash of Katanas - Wako - Rabble - Weapon (initiative)
12. Clash of Katanas - Wako - Veteran Bandits - Weapon (initiative)
13. Clash of Katanas - Joseon Koreans - Righteous Mob - Weapon (initiative)
14. Clash of Katanas - Ming Chinese - Mandarin Duck Melee Infantry - Weapon (initiative)

**Comment by cilliancleland** [comment]
Thanks for the report. I'll fix it up
