### ISSUE TITLE
Incorrect Throwing Spear points price

### ISSUE THREAD

**Issue by helg40k** [cilliancleland/clashculator#3]
Throwing Spear should cost 3 pts instead of 1.

How to check.

'Clash of Spears' rulebook.
p.124 - Options for character models

'Point System' pdf document
p.1 - Weapons table

Clashculator app.
Any level leader - Update to throwing spear

**Comment by cilliancleland** [comment]
Thanks for the report, I'll fix it up. Appreciate all the details too 😃
